client_config_backend: settings
client_config:
  client_id: 773987618584-trgdad7srctm58cbh788oovfeqi56r9n.apps.googleusercontent.com
  client_secret: gYxAdH5RYwIQoSJEJGOF7PjZ

save_credentials: True
save_credentials_backend: file 
save_credentials_file: credentials.json

get_refresh_token: True 

oauth_scope: 
    - https://www.googleapis.com/auth/drive
